services:
  comfyui:
    image: yanwk/comfyui-boot:cu129-slim
    volumes:
      - ./packages/comfyui-custom-nodes:/root/ComfyUI/custom_nodes/comfyui-custom-nodes
      - ./target/wheels:/wheels:ro
    ports:
      - "8188:8188"
    command: sh -c "pip install /wheels/comfyui_custom_nodes-0.1.0-cp312-abi3-manylinux_2_34_x86_64.whl --force-reinstall && bash /runner-scripts/entrypoint.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
