services:
  comfyui:
    image: yanwk/comfyui-boot:cu129-slim
    volumes:
      - ./packages/comfy-builder-custom-nodes:/root/ComfyUI/custom_nodes/comfy-builder-custom-nodes
      - ./target/wheels:/wheels:ro
    ports:
      - "8188:8188"
    command: sh -c "pip install /wheels/*.whl --force-reinstall && bash /runner-scripts/entrypoint.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
