[package]
name = "comfy-builder-custom-nodes"
version = "0.0.4"
edition = "2024"
description = "A system for building custom nodes for ComfyUI in Rust."
readme = "../../README.md"
repository = "https://github.com/milewski/comfy-node-builder"
homepage = "https://github.com/milewski/comfy-node-builder"
license = "MIT"
authors = ["Rafael Milewski <rafael.milewski@gmail.com>"]
keywords = ["comfy", "comfyui", "comfy-ui"]
categories = ["development-tools"]
exclude = [".git", ".github"]
rust-version = "1.90.0"

[lib]
name = "comfy_builder_custom_nodes"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0" }
comfy-builder-core = { version = "0.0.4", path = "../comfy-builder-core" }
inventory = "0.3.21"

[build-dependencies]
toml = "0.9.7"
