[package]
name = "comfy-builder-core"
version = "0.0.7"
edition = "2024"
description = "A system for building custom nodes for ComfyUI in Rust."
readme = "../../README.md"
repository = "https://github.com/milewski/comfy-builder"
homepage = "https://github.com/milewski/comfy-builder"
license = "MIT"
authors = ["Rafael Milewski <rafael.milewski@gmail.com>"]
keywords = ["comfy", "comfyui", "comfy-ui"]
categories = ["development-tools"]
exclude = [".git", ".github"]
rust-version = "1.90.0"

[lib]
name = "comfy_builder_core"

[dependencies]
pyo3 = { version = "0.26.0", features = ["abi3-py312", "experimental-async"] }
candle-core = "0.9.1"
comfy-builder-macros = { version = "0.0.7", path = "../comfy-builder-macros" }
numpy = "0.26.0"
inventory = "0.3.21"
num-traits = "0.2.19"
