[package]
name = "comfyui-plugin"
version.workspace = true
edition.workspace = true

[lib]
name = "comfyui_plugin"

[dependencies]
pyo3.workspace = true
candle-core.workspace = true
comfyui-macro.workspace = true
numpy = "0.26.0"
indexmap = "2.11.4"
inventory = "0.3.21"
