[package]
name = "comfy-builder-macros"
version = "0.0.4"
edition = "2024"
description = "A system for building custom nodes for ComfyUI in Rust."
readme = "../../README.md"
repository = "https://github.com/milewski/comfy-builder"
homepage = "https://github.com/milewski/comfy-builder"
license = "MIT"
authors = ["Rafael Milewski <rafael.milewski@gmail.com>"]
keywords = ["comfy", "comfyui", "comfy-ui"]
categories = ["development-tools"]
exclude = [".git", ".github"]
rust-version = "1.90.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = { version = "^2.0", features = ["full"] }
